### ISSUE TITLE
基金代码正确，但是无法获取数据

### ISSUE THREAD

**Issue by leong-cit** [1y0ng/boll-fund#1]
感谢你的代码，非常棒！
我在使用的时候碰到这个错误，如下：
` url='http://fundgz.1234567.com.cn/js/'+code+'.js?rt='+str(round(t * 1000))`
在拼接js的时候，明明基金代码是正确的，但是却找不到数据，比如014978，https://fundgz.1234567.com.cn/js/014978.js?rt=1731637717158
返回是空
<img width="778" alt="image" src="https://github.com/user-attachments/assets/ffcf8b8d-b4a6-4cd9-b00c-ae4f94368846">

**Comment by 1y0ng** [comment]
> 感谢你的代码，非常棒！ 我在使用的时候碰到这个错误，如下： ` url='http://fundgz.1234567.com.cn/js/'+code+'.js?rt='+str(round(t * 1000))` 在拼接js的时候，明明基金代码是正确的，但是却找不到数据，比如014978，https://fundgz.1234567.com.cn/js/014978.js?rt=1731637717158 返回是空 <img alt="image" width="778" src="https://private-user-images.githubusercontent.com/175274400/386442945-ffcf8b8d-b4a6-4cd9-b00c-ae4f94368846.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzE2NDc0NTcsIm5iZiI6MTczMTY0NzE1NywicGF0aCI6Ii8xNzUyNzQ0MDAvMzg2NDQyOTQ1LWZmY2Y4YjhkLWI0YTYtNGNkOS1iMDBjLWFlNGY5NDM2ODg0Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTE1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTExNVQwNTA1NTdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZjVlNjlmNjFmZjQ5ZDYwMTE4YTlmYmExMDBmZGU5MjQyYzQwYjg4MGUxZTgzMWRhYjQzZmVhYjgzZjg5ZTNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.r-mT0TagbHxfAyvFwl3IG2nIv1tQ0UZkTmbqNn_hPoo">

对于一些投资了国外股票的基金，该接口无法查询实时估值
